// Fallback and offline data for enterprise applications and licenses

export const mockApplications = [
  {
    application_id: 'app-ms365',
    application_name: 'Microsoft 365',
    application_code: 'M365',
    vendor_name: 'Microsoft Corporation',
    category: 'Productivity & Cloud',
    status: 'active',
    criticality: 'critical',
    business_unit: 'Global Enterprise',
    description: 'Enterprise Microsoft 365 tenant suite including Office 365, Teams, Power Platform, Defender & Dynamics 365.',
    licenses_count: 16,
    total_seats: 1040488,
    assigned_seats: 885,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: new Date().toISOString(),
  },
  {
    application_id: 'app-slack',
    application_name: 'Slack',
    application_code: 'SLACK',
    vendor_name: 'Slack Technologies / Salesforce',
    category: 'Communication',
    status: 'active',
    criticality: 'high',
    business_unit: 'IT & Engineering',
    description: 'Enterprise workspace collaboration and communication platform.',
    licenses_count: 1,
    total_seats: 12,
    assigned_seats: 11,
    created_at: '2024-01-25T09:00:00Z',
    updated_at: new Date().toISOString(),
  },
  {
    application_id: 'app-lucidchart',
    application_name: 'Lucidchart',
    application_code: 'LUCID',
    vendor_name: 'Lucid Software',
    category: 'Visual Collaboration',
    status: 'inactive',
    criticality: 'medium',
    business_unit: 'Product & Design',
    description: 'Visual collaboration suite and diagramming.',
    licenses_count: 0,
    total_seats: 0,
    assigned_seats: 0,
    created_at: '2024-02-10T00:00:00Z',
    updated_at: new Date().toISOString(),
  },
  {
    application_id: 'app-box',
    application_name: 'Box',
    application_code: 'BOX',
    vendor_name: 'Box Inc.',
    category: 'Cloud Storage',
    status: 'inactive',
    criticality: 'medium',
    business_unit: 'Corporate IT',
    description: 'Enterprise cloud content management and file storage.',
    licenses_count: 0,
    total_seats: 0,
    assigned_seats: 0,
    created_at: '2024-02-15T00:00:00Z',
    updated_at: new Date().toISOString(),
  },
  {
    application_id: 'app-zoom',
    application_name: 'Zoom',
    application_code: 'ZOOM',
    vendor_name: 'Zoom Video Communications',
    category: 'Video Conferencing',
    status: 'inactive',
    criticality: 'high',
    business_unit: 'Global Operations',
    description: 'Enterprise video communication and virtual meetings.',
    licenses_count: 0,
    total_seats: 0,
    assigned_seats: 0,
    created_at: '2024-03-01T00:00:00Z',
    updated_at: new Date().toISOString(),
  },
  {
    application_id: 'app-sofia',
    application_name: 'Sofia - (Pilot)',
    application_code: 'SOFIA',
    vendor_name: 'Sofia AI Labs',
    category: 'AI Assistant',
    status: 'inactive',
    criticality: 'medium',
    business_unit: 'Innovation & AI',
    description: 'Pilot generative AI assistant for internal operations.',
    licenses_count: 0,
    total_seats: 0,
    assigned_seats: 0,
    created_at: '2024-03-15T00:00:00Z',
    updated_at: new Date().toISOString(),
  },
  {
    application_id: 'app-jira',
    application_name: '_Jira',
    application_code: 'JIRA',
    vendor_name: 'Atlassian',
    category: 'Project Management',
    status: 'inactive',
    criticality: 'high',
    business_unit: 'Software Engineering',
    description: 'Issue & project tracking software for agile development.',
    licenses_count: 0,
    total_seats: 0,
    assigned_seats: 0,
    created_at: '2024-03-20T00:00:00Z',
    updated_at: new Date().toISOString(),
  },
  {
    application_id: 'app-cato',
    application_name: 'CATO',
    application_code: 'CATO',
    vendor_name: 'Cato Networks',
    category: 'SASE & Security',
    status: 'inactive',
    criticality: 'critical',
    business_unit: 'Cybersecurity & Infrastructure',
    description: 'Cloud-native SASE security and SD-WAN architecture.',
    licenses_count: 0,
    total_seats: 0,
    assigned_seats: 0,
    created_at: '2024-04-01T00:00:00Z',
    updated_at: new Date().toISOString(),
  },
];


export const mockLicenses = [
  // ── Microsoft 365 Licenses (All 16 Types) ──────────────────────────────────
  {
    license_id: 'ms-1',
    license_name: 'Microsoft 365 Business Premium',
    raw_sku_part_number: 'O365_BUSINESS_PREMIUM',
    product_code: 'O365_BUSINESS_PREMIUM',
    license_type: 'Business Suite',
    application_name: 'Microsoft 365',
    vendor: 'Microsoft',
    total_quantity: 166,
    allocated_quantity: 166,
    used_quantity: 166,
    available_quantity: 0,
    cost_amount: 43824, // $264 * 166
    currency: 'USD',
    billing_frequency: 'annual',
    status: 'active',
    expiry_date: '2026-12-31',
    auto_renew: true,
    source_system: 'Microsoft Graph API (Live Sync)',
    badgeColor: 'primary',
    description: 'Comprehensive productivity suite with advanced security & device management.',
  },
  {
    license_id: 'ms-2',
    license_name: 'Microsoft 365 Business Basic',
    raw_sku_part_number: 'O365_BUSINESS_ESSENTIALS',
    product_code: 'O365_BUSINESS_ESSENTIALS',
    license_type: 'Productivity & Cloud',
    application_name: 'Microsoft 365',
    vendor: 'Microsoft',
    total_quantity: 300,
    allocated_quantity: 300,
    used_quantity: 300,
    available_quantity: 0,
    cost_amount: 21600, // $72 * 300
    currency: 'USD',
    billing_frequency: 'annual',
    status: 'active',
    expiry_date: '2026-12-31',
    auto_renew: true,
    source_system: 'Microsoft Graph API (Live Sync)',
    badgeColor: 'info',
    description: 'Cloud services including web & mobile Office apps, Teams, Exchange & SharePoint.',
  },
  {
    license_id: 'ms-3',
    license_name: 'Office 365 E3 Enterprise',
    raw_sku_part_number: 'ENTERPRISEPACK',
    product_code: 'ENTERPRISEPACK',
    license_type: 'Enterprise Cloud',
    application_name: 'Microsoft 365',
    vendor: 'Microsoft',
    total_quantity: 1,
    allocated_quantity: 1,
    used_quantity: 1,
    available_quantity: 0,
    cost_amount: 276,
    currency: 'USD',
    billing_frequency: 'annual',
    status: 'active',
    expiry_date: '2026-12-31',
    auto_renew: true,
    source_system: 'Microsoft Graph API (Live Sync)',
    badgeColor: 'primary',
    description: 'Enterprise-grade productivity apps with compliance and data protection.',
  },
  {
    license_id: 'ms-4',
    license_name: 'Exchange Online (Plan 2)',
    raw_sku_part_number: 'EXCHANGEENTERPRISE',
    product_code: 'EXCHANGEENTERPRISE',
    license_type: 'Messaging & Email',
    application_name: 'Microsoft 365',
    vendor: 'Microsoft',
    total_quantity: 12,
    allocated_quantity: 12,
    used_quantity: 12,
    available_quantity: 0,
    cost_amount: 1152,
    currency: 'USD',
    billing_frequency: 'annual',
    status: 'active',
    expiry_date: '2026-12-31',
    auto_renew: true,
    source_system: 'Microsoft Graph API (Live Sync)',
    badgeColor: 'warning',
    description: 'Enterprise email, calendaring, unlimited archiving, and DLP compliance.',
  },
  {
    license_id: 'ms-5',
    license_name: 'Microsoft Teams Premium',
    raw_sku_part_number: 'Teams_Premium_(for_Departments)',
    product_code: 'Teams_Premium_(for_Departments)',
    license_type: 'Collaboration & Meetings',
    application_name: 'Microsoft 365',
    vendor: 'Microsoft',
    total_quantity: 1,
    allocated_quantity: 1,
    used_quantity: 1,
    available_quantity: 0,
    cost_amount: 120,
    currency: 'USD',
    billing_frequency: 'annual',
    status: 'active',
    expiry_date: '2026-12-31',
    auto_renew: true,
    source_system: 'Microsoft Graph API (Live Sync)',
    badgeColor: 'purple',
    description: 'Advanced AI meeting summaries, customized branding, and webinar features.',
  },
  {
    license_id: 'ms-6',
    license_name: 'Microsoft Power BI Pro',
    raw_sku_part_number: 'POWER_BI_PRO',
    product_code: 'POWER_BI_PRO',
    license_type: 'Analytics & BI',
    application_name: 'Microsoft 365',
    vendor: 'Microsoft',
    total_quantity: 2,
    allocated_quantity: 2,
    used_quantity: 2,
    available_quantity: 0,
    cost_amount: 240,
    currency: 'USD',
    billing_frequency: 'annual',
    status: 'active',
    expiry_date: '2026-12-31',
    auto_renew: true,
    source_system: 'Microsoft Graph API (Live Sync)',
    badgeColor: 'warning',
    description: 'Self-service analytics to visualize data and share interactive reports.',
  },
  {
    license_id: 'ms-7',
    license_name: 'Microsoft Power BI (Standard / Free)',
    raw_sku_part_number: 'POWER_BI_STANDARD',
    product_code: 'POWER_BI_STANDARD',
    license_type: 'Analytics & BI',
    application_name: 'Microsoft 365',
    vendor: 'Microsoft',
    total_quantity: 1000000,
    allocated_quantity: 92,
    used_quantity: 92,
    available_quantity: 999908,
    cost_amount: 0,
    currency: 'USD',
    billing_frequency: 'annual',
    status: 'active',
    expiry_date: '2027-12-31',
    auto_renew: true,
    source_system: 'Microsoft Graph API (Live Sync)',
    badgeColor: 'neutral',
    description: 'Standard access for personal analytics and report viewing.',
  },
  {
    license_id: 'ms-8',
    license_name: 'Microsoft Power Automate (Free)',
    raw_sku_part_number: 'FLOW_FREE',
    product_code: 'FLOW_FREE',
    license_type: 'Automation & Workflows',
    application_name: 'Microsoft 365',
    vendor: 'Microsoft',
    total_quantity: 10000,
    allocated_quantity: 260,
    used_quantity: 260,
    available_quantity: 9740,
    cost_amount: 0,
    currency: 'USD',
    billing_frequency: 'annual',
    status: 'active',
    expiry_date: '2027-12-31',
    auto_renew: true,
    source_system: 'Microsoft Graph API (Live Sync)',
    badgeColor: 'neutral',
    description: 'Workflow automation across business applications and services.',
  },
  {
    license_id: 'ms-9',
    license_name: 'Microsoft Power Apps for Developer',
    raw_sku_part_number: 'POWERAPPS_DEV',
    product_code: 'POWERAPPS_DEV',
    license_type: 'Developer & Sandbox',
    application_name: 'Microsoft 365',
    vendor: 'Microsoft',
    total_quantity: 10000,
    allocated_quantity: 16,
    used_quantity: 16,
    available_quantity: 9984,
    cost_amount: 0,
    currency: 'USD',
    billing_frequency: 'annual',
    status: 'active',
    expiry_date: '2027-12-31',
    auto_renew: true,
    source_system: 'Microsoft Graph API (Live Sync)',
    badgeColor: 'info',
    description: 'Dedicated sandbox environment for testing Power Apps and Dataverse.',
  },
  {
    license_id: 'ms-10',
    license_name: 'Microsoft Defender Threat Intelligence',
    raw_sku_part_number: 'THREAT_INTELLIGENCE',
    product_code: 'THREAT_INTELLIGENCE',
    license_type: 'Cybersecurity & Identity',
    application_name: 'Microsoft 365',
    vendor: 'Microsoft',
    total_quantity: 5,
    allocated_quantity: 4,
    used_quantity: 4,
    available_quantity: 1,
    cost_amount: 2400,
    currency: 'USD',
    billing_frequency: 'annual',
    status: 'active',
    expiry_date: '2026-12-31',
    auto_renew: true,
    source_system: 'Microsoft Graph API (Live Sync)',
    badgeColor: 'danger',
    description: 'Direct visibility into threat actor infrastructure and proactive defenses.',
  },
  {
    license_id: 'ms-11',
    license_name: 'Dynamics 365 Sales Premium (Trial)',
    raw_sku_part_number: 'Dynamics_365_Sales_Premium_Viral_Trial',
    product_code: 'Dynamics_365_Sales_Premium_Viral_Trial',
    license_type: 'CRM & Sales',
    application_name: 'Microsoft 365',
    vendor: 'Microsoft',
    total_quantity: 10000,
    allocated_quantity: 5,
    used_quantity: 5,
    available_quantity: 9995,
    cost_amount: 8100,
    currency: 'USD',
    billing_frequency: 'annual',
    status: 'active',
    expiry_date: '2026-12-31',
    auto_renew: true,
    source_system: 'Microsoft Graph API (Live Sync)',
    badgeColor: 'success',
    description: 'Sales automation with predictive forecasting and relationship intelligence.',
  },
  {
    license_id: 'ms-12',
    license_name: 'Dynamics 365 Customer Service Enterprise',
    raw_sku_part_number: 'Dynamics_365_Customer_Service_Enterprise_viral_trial',
    product_code: 'Dynamics_365_Customer_Service_Enterprise_viral_trial',
    license_type: 'Customer Support',
    application_name: 'Microsoft 365',
    vendor: 'Microsoft',
    total_quantity: 10000,
    allocated_quantity: 3,
    used_quantity: 3,
    available_quantity: 9997,
    cost_amount: 3780,
    currency: 'USD',
    billing_frequency: 'annual',
    status: 'active',
    expiry_date: '2026-12-31',
    auto_renew: true,
    source_system: 'Microsoft Graph API (Live Sync)',
    badgeColor: 'info',
    description: 'Omnichannel customer support, case routing, and agent collaboration.',
  },
  {
    license_id: 'ms-13',
    license_name: 'Microsoft Power Pages Maker Trial',
    raw_sku_part_number: 'Power_Pages_vTrial_for_Makers',
    product_code: 'Power_Pages_vTrial_for_Makers',
    license_type: 'Low-Code Web Apps',
    application_name: 'Microsoft 365',
    vendor: 'Microsoft',
    total_quantity: 10000,
    allocated_quantity: 4,
    used_quantity: 4,
    available_quantity: 9996,
    cost_amount: 0,
    currency: 'USD',
    billing_frequency: 'annual',
    status: 'active',
    expiry_date: '2026-12-31',
    auto_renew: true,
    source_system: 'Microsoft Graph API (Live Sync)',
    badgeColor: 'neutral',
    description: 'Secure, low-code platform for building external business web portals.',
  },
  {
    license_id: 'ms-14',
    license_name: 'Dynamics 365 Finance & Operations',
    raw_sku_part_number: 'AX7_USER_TRIAL',
    product_code: 'AX7_USER_TRIAL',
    license_type: 'Enterprise ERP',
    application_name: 'Microsoft 365',
    vendor: 'Microsoft',
    total_quantity: 10000,
    allocated_quantity: 3,
    used_quantity: 3,
    available_quantity: 9997,
    cost_amount: 6480,
    currency: 'USD',
    billing_frequency: 'annual',
    status: 'active',
    expiry_date: '2026-12-31',
    auto_renew: true,
    source_system: 'Microsoft Graph API (Live Sync)',
    badgeColor: 'purple',
    description: 'Global enterprise financials, supply chain, and manufacturing management.',
  },
  {
    license_id: 'ms-15',
    license_name: 'Dynamics 365 Business Central',
    raw_sku_part_number: 'PROJECT_MADEIRA_PREVIEW_IW_SKU',
    product_code: 'PROJECT_MADEIRA_PREVIEW_IW_SKU',
    license_type: 'Cloud ERP',
    application_name: 'Microsoft 365',
    vendor: 'Microsoft',
    total_quantity: 10000,
    allocated_quantity: 2,
    used_quantity: 2,
    available_quantity: 9998,
    cost_amount: 1680,
    currency: 'USD',
    billing_frequency: 'annual',
    status: 'active',
    expiry_date: '2026-12-31',
    auto_renew: true,
    source_system: 'Microsoft Graph API (Live Sync)',
    badgeColor: 'primary',
    description: 'All-in-one business management for SMB finance, sales, service, and operations.',
  },
  {
    license_id: 'ms-16',
    license_name: 'Microsoft Copilot Studio / Bot Services',
    raw_sku_part_number: 'CCIBOTS_PRIVPREV_VIRAL',
    product_code: 'CCIBOTS_PRIVPREV_VIRAL',
    license_type: 'AI & Copilot Studio',
    application_name: 'Microsoft 365',
    vendor: 'Microsoft',
    total_quantity: 10000,
    allocated_quantity: 14,
    used_quantity: 14,
    available_quantity: 9986,
    cost_amount: 33600,
    currency: 'USD',
    billing_frequency: 'annual',
    status: 'active',
    expiry_date: '2026-12-31',
    auto_renew: true,
    source_system: 'Microsoft Graph API (Live Sync)',
    badgeColor: 'purple',
    description: 'Custom AI conversational copilots with natural language understanding.',
  },

  // ── Slack License ─────────────────────────────────────────────────────────
  {
    license_id: 'slack-1',
    license_name: 'Slack Pro',
    raw_sku_part_number: 'SLACK_PRO',
    product_code: 'SLACK_PRO',
    license_type: 'Team Collaboration',
    application_name: 'Slack',
    vendor: 'Slack Technologies / Salesforce',
    total_quantity: 12,
    allocated_quantity: 11,
    used_quantity: 5,
    available_quantity: 1,
    billing_frequency: 'annual',
    status: 'active',
    expiry_date: '2026-11-15',
    auto_renew: true,
    source_system: 'Slack SCIM / REST API (Live Sync)',
    badgeColor: 'purple',
    description: 'Enterprise team messaging and collaboration workspace.',
  },
];

export const mockSummary = {
  total_applications: 8,
  active_applications: 2,
  inactive_applications: 6,
  total_licenses: 17,
  total_seats: 1040500,
  used_licenses: 896,
  available_licenses: 1039604,
  utilization_percentage: 85.0,
  expiring_30_days: 0,
  expiring_90_days: 1,
};

export const mockUtilization = [
  { name: 'M365 Business Premium', used: 166, total: 166, utilization: 100.0 },
  { name: 'M365 Business Basic', used: 300, total: 300, utilization: 100.0 },
  { name: 'Slack Pro', used: 11, total: 12, utilization: 91.7 },
  { name: 'Exchange Online (P2)', used: 12, total: 12, utilization: 100.0 },
  { name: 'Power Automate (Free)', used: 260, total: 10000, utilization: 2.6 },
  { name: 'Power BI (Standard)', used: 92, total: 1000000, utilization: 0.01 },
  { name: 'Power Apps Dev', used: 16, total: 10000, utilization: 0.2 },
  { name: 'Copilot Studio', used: 14, total: 10000, utilization: 0.1 },
];

export const mockExpiring = [
  {
    license_id: 'slack-1',
    license_name: 'Slack Pro',
    application_name: 'Slack',
    expiry_date: '2026-11-15',
    days_remaining: 40,
    allocated_quantity: 11,
    total_quantity: 12,
  },
  {
    license_id: 'ms-1',
    license_name: 'Microsoft 365 Business Premium',
    application_name: 'Microsoft 365',
    expiry_date: '2026-12-31',
    days_remaining: 86,
    allocated_quantity: 166,
    total_quantity: 166,
  },
];

export const mockSeatDistribution = [
  { name: 'Microsoft 365', seats: 885, totalSeats: 1040488 },
  { name: 'Slack', seats: 11, totalSeats: 12 },
  { name: 'Lucidchart', seats: 0, totalSeats: 0 },
  { name: 'Box', seats: 0, totalSeats: 0 },
  { name: 'Zoom', seats: 0, totalSeats: 0 },
  { name: 'Sofia - (Pilot)', seats: 0, totalSeats: 0 },
  { name: '_Jira', seats: 0, totalSeats: 0 },
  { name: 'CATO', seats: 0, totalSeats: 0 },
];

export const mockUsers = [
  // Microsoft 365 Users
  { user_id: 1, name: 'Adele Vance', email: 'AdeleV@m365x.onmicrosoft.com', role: 'Product Marketing Manager', status: 'active', department: 'Marketing', application_name: 'Microsoft 365', license_id: 'ms-1', assigned_date: '2024-01-15' },
  { user_id: 2, name: 'Alex Wilber', email: 'AlexW@m365x.onmicrosoft.com', role: 'Marketing Assistant', status: 'active', department: 'Marketing', application_name: 'Microsoft 365', license_id: 'ms-1', assigned_date: '2024-02-01' },
  { user_id: 3, name: 'Megan Bowen', email: 'MeganB@m365x.onmicrosoft.com', role: 'Director', status: 'active', department: 'Executive', application_name: 'Microsoft 365', license_id: 'ms-1', assigned_date: '2024-01-10' },
  { user_id: 4, name: 'Diego Siciliani', email: 'DiegoS@m365x.onmicrosoft.com', role: 'Lead Specialist', status: 'active', department: 'Sales', application_name: 'Microsoft 365', license_id: 'ms-2', assigned_date: '2024-02-12' },
  { user_id: 5, name: 'Henrietta Mueller', email: 'HenriettaM@m365x.onmicrosoft.com', role: 'Operations Lead', status: 'active', department: 'Operations', application_name: 'Microsoft 365', license_id: 'ms-2', assigned_date: '2024-03-05' },
  { user_id: 6, name: 'Joni Sherman', email: 'JoniS@m365x.onmicrosoft.com', role: 'Security Analyst', status: 'active', department: 'IT Security', application_name: 'Microsoft 365', license_id: 'ms-3', assigned_date: '2024-03-18' },
  { user_id: 7, name: 'Lynne Robbins', email: 'LynneR@m365x.onmicrosoft.com', role: 'Exchange Admin', status: 'active', department: 'Infrastructure', application_name: 'Microsoft 365', license_id: 'ms-4', assigned_date: '2024-01-20' },

  // Slack Users
  { user_id: 8, name: 'Praveen Kumar', email: 'praveen@clouddestinations.com', role: 'Owner / Tech Lead', status: 'active', department: 'Engineering', application_name: 'Slack', license_id: 'slack-1', assigned_date: '2024-01-25' },
  { user_id: 9, name: 'Jerry Jones', email: 'jerryj@clouddestinations.com', role: 'Member / DevOps', status: 'active', department: 'IT', application_name: 'Slack', license_id: 'slack-1', assigned_date: '2024-01-26' },
  { user_id: 10, name: 'Sarah Connor', email: 'sarah.c@company.internal', role: 'Product Manager', status: 'active', department: 'Product', application_name: 'Slack', license_id: 'slack-1', assigned_date: '2024-02-05' },
  { user_id: 11, name: 'David Chen', email: 'david.chen@company.internal', role: 'Fullstack Engineer', status: 'active', department: 'Engineering', application_name: 'Slack', license_id: 'slack-1', assigned_date: '2024-02-14' },

  // Lucidchart Users
  { user_id: 12, name: 'Elena Rostova', email: 'elena.r@company.internal', role: 'Solution Architect', status: 'active', department: 'Architecture', application_name: 'Lucidchart', license_id: 'lucid-1', assigned_date: '2024-02-10' },
  { user_id: 13, name: 'Marcus Brody', email: 'marcus.b@company.internal', role: 'UX Lead', status: 'active', department: 'Design', application_name: 'Lucidchart', license_id: 'lucid-1', assigned_date: '2024-02-18' },
  { user_id: 14, name: 'Chloe Kim', email: 'chloe.k@company.internal', role: 'Systems Analyst', status: 'active', department: 'Product & Design', application_name: 'Lucidchart', license_id: 'lucid-1', assigned_date: '2024-03-01' },

  // Box Users
  { user_id: 15, name: 'Robert Vance', email: 'robert.v@company.internal', role: 'Legal Counsel', status: 'active', department: 'Legal & Compliance', application_name: 'Box', license_id: 'box-1', assigned_date: '2024-02-15' },
  { user_id: 16, name: 'Samantha Reed', email: 'samantha.r@company.internal', role: 'Finance Director', status: 'active', department: 'Finance', application_name: 'Box', license_id: 'box-1', assigned_date: '2024-02-20' },
  { user_id: 17, name: 'Ethan Hunt', email: 'ethan.h@company.internal', role: 'Records Manager', status: 'inactive', department: 'Corporate IT', application_name: 'Box', license_id: 'box-1', assigned_date: '2024-03-10' },

  // Zoom Users
  { user_id: 18, name: 'Rachel Green', email: 'rachel.g@company.internal', role: 'Sales Lead', status: 'active', department: 'Commercial Sales', application_name: 'Zoom', license_id: 'zoom-1', assigned_date: '2024-03-01' },
  { user_id: 19, name: 'Michael Scott', email: 'michael.s@company.internal', role: 'Branch Director', status: 'active', department: 'Global Operations', application_name: 'Zoom', license_id: 'zoom-1', assigned_date: '2024-03-05' },
  { user_id: 20, name: 'Jim Halpert', email: 'jim.h@company.internal', role: 'Key Account Manager', status: 'active', department: 'Commercial Sales', application_name: 'Zoom', license_id: 'zoom-1', assigned_date: '2024-03-12' },

  // Sofia Pilot Users
  { user_id: 21, name: 'Dr. Evelyn Harper', email: 'evelyn.h@company.internal', role: 'Principal AI Researcher', status: 'active', department: 'Innovation & AI', application_name: 'Sofia - (Pilot)', license_id: 'sofia-1', assigned_date: '2024-03-15' },
  { user_id: 22, name: 'Liam Foster', email: 'liam.f@company.internal', role: 'Pilot Participant / Engineer', status: 'active', department: 'Software Engineering', application_name: 'Sofia - (Pilot)', license_id: 'sofia-1', assigned_date: '2024-03-18' },
  { user_id: 23, name: 'Nora Vasquez', email: 'nora.v@company.internal', role: 'Product Tester', status: 'active', department: 'Innovation & AI', application_name: 'Sofia - (Pilot)', license_id: 'sofia-1', assigned_date: '2024-03-25' },

  // Jira Users
  { user_id: 24, name: 'Arthur Pendelton', email: 'arthur.p@company.internal', role: 'Scrum Master', status: 'active', department: 'Software Engineering', application_name: '_Jira', license_id: 'jira-1', assigned_date: '2024-03-20' },
  { user_id: 25, name: 'Carlos Mendez', email: 'carlos.m@company.internal', role: 'Senior Backend Engineer', status: 'active', department: 'Software Engineering', application_name: '_Jira', license_id: 'jira-1', assigned_date: '2024-03-22' },
  { user_id: 26, name: 'Grace Hopper', email: 'grace.h@company.internal', role: 'QA Automation Lead', status: 'active', department: 'Quality Assurance', application_name: '_Jira', license_id: 'jira-1', assigned_date: '2024-04-02' },

  // CATO Users
  { user_id: 27, name: 'Vikram Patel', email: 'vikram.p@company.internal', role: 'Network Security Architect', status: 'active', department: 'Cybersecurity & Infrastructure', application_name: 'CATO', license_id: 'cato-1', assigned_date: '2024-04-01' },
  { user_id: 28, name: 'Diana Prince', email: 'diana.p@company.internal', role: 'Cloud SOC Engineer', status: 'active', department: 'Cybersecurity', application_name: 'CATO', license_id: 'cato-1', assigned_date: '2024-04-05' },
  { user_id: 29, name: 'Lucas Scott', email: 'lucas.s@company.internal', role: 'Infrastructure Engineer', status: 'inactive', department: 'Infrastructure', application_name: 'CATO', license_id: 'cato-1', assigned_date: '2024-04-10' },
];

export const mockSyncJobs = [
  {
    id: 1,
    sync_job_id: 1,
    connector_id: 'ms-graph',
    application_name: 'Microsoft 365',
    started_at: new Date(Date.now() - 1800000).toISOString(),
    completed_at: new Date(Date.now() - 1770000).toISOString(),
    status: 'success',
    records_processed: 16,
    records_created: 16,
    records_updated: 0,
    records_failed: 0,
    error_message: null,
  },
  {
    id: 2,
    sync_job_id: 2,
    connector_id: 'slack-api',
    application_name: 'Slack',
    started_at: new Date(Date.now() - 3600000).toISOString(),
    completed_at: new Date(Date.now() - 3590000).toISOString(),
    status: 'success',
    records_processed: 12,
    records_created: 1,
    records_updated: 11,
    records_failed: 0,
    error_message: null,
  },
];
